export const SET_CATEGORIES = 'SET_CATEGORIES';
export const SET_PRODUCTS = 'SET_PRODUCTS';
export const SET_PRODUCT = 'SET_PRODUCT';
export const SET_LOADING = 'SET_LOADING';
export const SET_CURRENT_CATEGORY = 'SET_CURRENT_CATEGORY'; 